#!/usr/bin/ruby

class Customer
   @@no_of_customers=0
   def initialize(id, name, addr)
      @cust_id=id
      @cust_name=name
      @cust_addr=addr
   end
   def display_details()
      puts "Customer id #@cust_id"
      puts "Customer name #@cust_name"
      puts "Customer address #@cust_addr"
   end
   def total_no_of_customers()
      @@no_of_customers += 1
      puts "Total number of customers: #@@no_of_customers"
   end
end

# Create Objects
cust1=Customer.new("1", "John", "Wisdom Apartments, Ludhiya")
cust2=Customer.new("2", "Poul", "New Empire road, Khandala")

# Call Methods
cust1.display_details()
cust1.total_no_of_customers()
cust2.display_details()
cust2.total_no_of_customers()
(10..15).each do |n| 
  # print n, ' ' 
end
nums = Array.new(10) { |e| e = e * 2 }
n2=Array(0..20)
puts "*************"
puts n2.at(6)
time1 = Time.new
puts "Current Time : " + time1.inspect
puts time1.strftime("%Y%m%d%H%M")
rang1=('abc'..'abf').to_a
puts "#{rang1}"
#################
a = [1,2,3,4,5]
b = a.collect{|x| 10**x}
puts b
############
puts "##########"
puts "Enter a value :"
val = gets

#*****************
begin
  
file = open("#{val.chop}")

   if file
      puts "File opened successfully"
   end
rescue
      file = STDIN
print file, "==", STDIN, " "
end
